name: Deploy Laravel App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, curl, mysql, zip
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set Laravel Permissions
      run: chmod -R 775 storage bootstrap/cache

    - name: Zip Laravel App for Deployment
      run: |
        zip -r deploy.zip . -x ".git/*" ".github/*" "tests/*" "node_modules/*" "vendor/*"

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
        echo "APP_ENV=production" >> .env
        echo "APP_DEBUG=false" >> .env

    - name: Laravel Artisan Commands
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DartTest
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
