name: Deploy Laravel App to Azure

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, curl, mysql, zip
        coverage: none
    
    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        composer --version

    - name: Install Composer Dependencies (verbose)
      run: composer install --no-dev --optimize-autoloader -vvv || true

    - name: Set Laravel Permissions
      run: |
        chmod -R 775 storage bootstrap/cache

    - name: Generate Application Key (optional)
      run: php artisan key:generate
      env:
        APP_KEY: ${{ secrets.APP_KEY }}

    - name: Cache Laravel Config
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DartTest
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
